version: 0.0            # CodeDeploy 버전 (고정)
os: linux               # 대상 OS

files:                  # S3에서 가져온 파일 배치 설정
  - source: /           # ZIP 루트 기준
    destination: /home/ubuntu/TOOCK-Backend  # EC2에 배치될 경로
    overwrite: yes      # 기존 파일 덮어쓰기

permissions:            # 배포된 디렉토리 권한 설정
  - object: /home/ubuntu/TOOCK-Backend
    owner: ubuntu
    group: ubuntu
    mode: 755           # 읽기/실행 권한

hooks:                  # 배포 후 실행할 스크립트 설정
  ApplicationStart:     # 파일 배치 후 애플리케이션 시작 단계
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
