spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  cloud:
    aws:
      credentials:
        access-key: aws-access-key
        secret-key: aws-secret-key
      region:
        static: ap-northeast-2
      s3:
        bucket: s3-bucket
      stack:
        auto: false