spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

openai:
  api:
    key: test-api-key
    timeout: 60

whisper:
  upload:
    dir: test-uploads/audio

gemini:
  api:
    key: test-api-key
