spring:
  datasource:
    url: ${LOCAL_MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_MYSQL_USERNAME}
    password: ${LOCAL_MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

  # Google OAuth2 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

openai:
  api:
    key: ${OPENAI_API_KEY}
    timeout: 60

whisper:
  upload:
    dir: uploads/audio

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000  # 24시간

app:
  oauth2:
    success-url: ${OAUTH2_SUCCESS_URL}
    failure-url: ${OAUTH2_FAILURE_URL}
