spring:
  datasource:
    url: ${LOCAL_MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_MYSQL_USERNAME}
    password: ${LOCAL_MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

openai:
  api:
    key: ${OPENAI_API_KEY:}
    timeout: 60

whisper:
  upload:
    dir: uploads/audio
