spring:
  datasource:
    url: #{DATASOURCE_URL}
    username: #{DATASOURCE_USERNAME}
    password: #{DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: #{GOOGLE_CLIENT_ID}
            client-secret: #{GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

openai:
  api:
    key: #{OPENAI_API_KEY}
    timeout: 60

whisper:
  upload:
    dir: uploads/audio

gemini:
  api:
    key: #GEMINI_API_KEY

# JWT 설정
jwt:
  secret: #{JWT_SECRET}
  expiration: 86400000

