ALTER TABLE member DROP COLUMN password;

ALTER TABLE member ADD COLUMN google_id VARCHAR(255) NULL AFTER field;

ALTER TABLE member 
  MODIFY COLUMN field ENUM('DEFAULT','BACKEND','FRONTEND','DEVOPS','DATA_SCIENCE','AI','SECURITY') NOT NULL;